Repository JensvandeWiel/ArkAscendedServerManager, pull requests merged in 2023-11, with the labels that each got.

#68 Changed screenshots in readme
  README.md
Labels: documentation, duplicate

#69 Add a option to disable update on start
  frontend/src/pages/Server.tsx
  frontend/src/pages/server/Administration.tsx
  server/helpers.go
  server/server.go
  server/server_controller.go
Labels: enhancement

#91 Add api auth system
  .github/workflows/main.yml
  .github/workflows/nightly.yaml
  .gitignore
  main.go
Labels: enhancement

#125 Autosave dividing by zero
  frontend/src/App.tsx
  frontend/src/pages/server/Administration.tsx
  server/helpers.go
  server/server_controller.go
Labels: bug

#134 updated multipliers tab layout
  .vscode/settings.json
  frontend/src/pages/server/Multipliers.tsx
Labels: enhancement
